language: php

php:
  - '7.2'
  - '7.3'

install:
   - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then
      sonar-scanner;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "evoluty-github"
